// Mocks generated by Mockito 5.3.2 from annotations
// in flutter_mockito_unit_test/test/album_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_mockito_unit_test/album_dto.dart' as _i2;
import 'package:flutter_mockito_unit_test/api_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAlbumDto_0 extends _i1.SmartFake implements _i2.AlbumDto {
  _FakeAlbumDto_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiRepository extends _i1.Mock implements _i3.ApiRepository {
  MockApiRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.AlbumDto> fetchAlbum() => (super.noSuchMethod(
        Invocation.method(
          #fetchAlbum,
          [],
        ),
        returnValue: _i4.Future<_i2.AlbumDto>.value(_FakeAlbumDto_0(
          this,
          Invocation.method(
            #fetchAlbum,
            [],
          ),
        )),
      ) as _i4.Future<_i2.AlbumDto>);
}
